# Here is an example Graviton configuration file.
# Currently just MongoDB is supported. But other
# databases will be supported future. If more than
# one database is added to a config you will need
# to specify which database to use when running
# commands.

[[databases]]
name = "example"
kind = "mongodb"
connection_url = "mongodb://localhost:27017"
database_name = "test"
migrations_path = "migrations"
